name: Upload Seats to Seats.io

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # ✅ FIXED: not 3.1

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run chart importer
        env:
          SEATSIO_SECRET_KEY: ${{ secrets.SEATSIO_SECRET_KEY }}
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
        run: python main.py
