name: Seats Chart Builder

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Remove old package/install fresh
        run: |
          pip uninstall -y seatsio || true
          rm -rf ~/.cache/pip
          pip install --upgrade pip
          pip install seatsio==81.8.0

      - name: Create credentials file
        run: echo '${{ secrets.GOOGLE_CREDENTIALS_JSON }}' > google_credentials.json

      - name: Run script
        env:
          SEATSIO_SECRET_KEY: ${{ secrets.SEATSIO_SECRET_KEY }}
          SEATSIO_CHART_KEY: ${{ secrets.SEATSIO_CHART_KEY }}
        run: python main.py
