name: Auto Create Seats.io Chart

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: |
          pip install gspread oauth2client seatsio==44.0.0

      - name: Create Google credentials file
        run: echo '${{ secrets.GOOGLE_CREDENTIALS_JSON }}' > google_credentials.json

      - name: Run main script
        env:
          SEATSIO_SECRET_KEY: ${{ secrets.SEATSIO_SECRET_KEY }}
          SEATSIO_WORKSPACE_KEY: ${{ secrets.SEATSIO_WORKSPACE_KEY }}
          SEATSIO_CHART_KEY: ${{ secrets.SEATSIO_CHART_KEY }}
        run: python main.py
