name: Generate Seats CSV

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run the main script
        run: python main.py

      - name: Upload CSV file
        uses: actions/upload-artifact@v4
        with:
          name: seatsio_ready_csv
          path: seatsio_ready.csv
