name: Upload Seats to Seats.io

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      # ✅ Add this step to expose GitHub Secrets
      - name: Export secrets to env
        run: |
          echo "GOOGLE_CREDENTIALS_JSON=${{ secrets.GOOGLE_CREDENTIALS_JSON }}" >> $GITHUB_ENV
          echo "SEATSIO_API_KEY=${{ secrets.SEATSIO_API_KEY }}" >> $GITHUB_ENV

      - name: Run main script
        run: python main.py
