name: Upload Seats to Seats.io

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Create Google creds file from secret
        run: echo "${{ secrets.GOOGLE_CREDENTIALS_JSON }}" > google_creds.json

      - name: Set environment vars
        run: |
          echo "GOOGLE_CREDENTIALS_FILE=google_creds.json" >> $GITHUB_ENV
          echo "SEATSIO_API_KEY=${{ secrets.SEATSIO_API_KEY }}" >> $GITHUB_ENV

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run upload script
        run: python main.py
