name: Upload Seats to Seats.io

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: 🧹 Clean broken package (seatsio)
        run: |
          pip uninstall -y seatsio || true
          rm -rf /opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/seatsio
          pip cache purge || true

      - name: Install correct packages
        run: pip install --upgrade pip && pip install -r requirements.txt

      - name: Run main script
        env:
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
          SEATSIO_API_KEY: ${{ secrets.SEATSIO_API_KEY }}
        run: python main.py
